logger:
  bot:
    starting: "Starting %bot.name v%bot.version..."
    started: "%bot.name has started!"
  config:
    reloading: "Reloading %bot.name..."
    reloaded: "Reloaded!"
commands:
  coolness: "I have decided you are %1% cool."
  reload: "The config files have been reloaded."
  count: "There are %1 characters in your message."
  random: "I have generated the number %1"